library(dplyr)
setwd(".")
df <- read.table("../household_power_consumption.txt", header=T, sep=";")
df$Date <- as.Date(df$Date, "%d/%m/%Y")
daysDF <- subset(df, Date == '2007-02-01' | Date == '2007-02-02')
daysDF$Global_active_power <- as.numeric(as.character(daysDF$Global_active_power))
daysDF$Sub_metering_2 <- as.numeric(as.character(daysDF$Sub_metering_2))
daysDF$Sub_metering_1 <- as.numeric(as.character(daysDF$Sub_metering_1))
daysDF$Global_reactive_power <- as.numeric(as.character(daysDF$Global_reactive_power))
daysDF$Voltage <- as.numeric(as.character(daysDF$Voltage))
daysDF <- mutate(daysDF, dateTime = paste(daysDF$Date, daysDF$Time, sep=" "))
daysDF$dateTime <- strptime(daysDF$dateTime, "%Y-%m-%d %H:%M:%S")

# Make the line graph, for plot2.PNG
png(file="plot2.PNG", bg="transparent")
plot(daysDF$dateTime,daysDF$Global_active_power, type="l", main="Global Active Power per Day", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()